* ebf

Brainfuck language transpiler to Emacs Lisp

** Usage

The brainfuck language transpiler to Emacs Lisp consists of ~ebf~
macro which expands to the actual Emacs Lisp code. Here is the
signature of this macro:

#+BEGIN_SRC emacs-lisp

(ebf INPUT-CALLBACK OUTPUT-CALLBACK &rest INSTRUCTIONS)

#+END_SRC

~INPUT-CALLBACK~ is called on comma instruction and should have zero
arguments and return a number.

~OUTPUT-CALLBACK~ is called on dot instruction and should have one
argument of an integer type.

~INSTRUCTIONS~ is a list of symbols and vectors of symbols. Vectors
are accepted so you don't need to escape square brackets of your
brainfuck program. Symbols' names should be sequences of valid
brainfuck instructions except square brackets.

Evaluation of the macro expansion causes the brainfuck program
execution.

So the code

#+BEGIN_SRC emacs-lisp
(ebf input output \,+++[->+<].)
#+END_SRC

will be expanded to

#+BEGIN_SRC emacs-lisp
(let ((MEMORY32194 (make-vector 100 0))
      (POINTER32195 0)
      (INPUT32192 input)
      (OUTPUT32193 output))
  (aset MEMORY32194 POINTER32195 (funcall INPUT32192))
  (cl-incf (aref MEMORY32194 POINTER32195))
  (cl-incf (aref MEMORY32194 POINTER32195))
  (cl-incf (aref MEMORY32194 POINTER32195))
  (while (not (zerop (aref MEMORY32194 POINTER32195)))
    (cl-decf (aref MEMORY32194 POINTER32195))
    (cl-incf POINTER32195)
    (cl-incf (aref MEMORY32194 POINTER32195))
    (cl-decf POINTER32195))
  (funcall OUTPUT32193 (aref MEMORY32194 POINTER32195)))
#+END_SRC

As you can see we don't do any optimizations and have a memory
limitation. But we are working on that.

Here is the classical Hello World example with some output:

#+BEGIN_SRC emacs-lisp
(let ((result nil))
  (ebf nil #'(lambda (x) (push x result))
       ++++++++++[>+++++++>++++++++++>+++>+<<<<-]>++
       .>+.+++++++..+++.>++.<<+++++++++++++++.>.+++.
       ------.--------.>+.>.)
  (apply #'string (reverse result)));<- put cursor here and press C-x C-e
#+END_SRC

** License

Copyright (C) 2015 Alexey Kutepov a.k.a rexim

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
